#pragma once

namespace forehead {

// Index-aligned with the ANIMALS slice in ForeheadWords.h. ASCII spelling is
// deliberate: the large card font contains no umlaut glyphs.
inline constexpr const char* kGermanAnimals[] = {
    "ALLIGATOR", "ALPAKA", "AMEISENBAER", "ANTILOPE", "GUERTELTIER", "PAVIAN", "DACHS", "SCHLEIEREULE",
    "FLEDERMAUS", "BAER", "BIBER", "BIENE", "KAEFER", "VOGEL", "BISON", "SCHWARZBAER", "BLAUWAL",
    "BULLDOGGE", "HUMMEL", "SCHMETTERLING", "KAMEL", "KATZE", "RAUPE", "HUNDERTFUESSER", "CHAMAELEON",
    "GEPARD", "HUHN", "CHIHUAHUA", "SCHIMPANSE", "STREIFENHOERNCHEN", "CLOWNFISCH", "KOBRA", "KAKERLAKE",
    "KUH", "KOJOTE", "KRABBE", "KROKODIL", "KRAEHE", "HIRSCH", "HUND", "DELFIN", "ESEL", "LIBELLE",
    "ENTE", "ADLER", "REGENWURM", "AAL", "ELEFANT", "WAPITI", "EMU", "FALKE", "FRETTCHEN", "GLUEHWUERMCHEN",
    "FISCH", "FLAMINGO", "FUCHS", "FROSCH", "GAZELLE", "GECKO", "RENNMAUS", "GROSSER PANDA", "GIRAFFE",
    "ZIEGE", "GOLDFISCH", "GANS", "GORILLA", "HEUSCHRECKE", "WINDHUND", "GRIZZLYBAER", "MEERSCHWEINCHEN",
    "HAMSTER", "IGEL", "EINSIEDLERKREBS", "REIHER", "NILPFERD", "HORNISSE", "PFERD", "KOLIBRI", "HYAENE",
    "LEGUAN", "JAGUAR", "QUALLE", "KAENGURU", "SCHWERTWAL", "EISVOGEL", "KOALA", "KOMODOWARAN",
    "MARIENKAEFER", "LEMUR", "LEOPARD", "LOEWE", "EIDECHSE", "LAMA", "HUMMER", "LUCHS", "ARA", "ELSTER",
    "MANATI", "ERDMAENNCHEN", "MAULWURF", "MANGUSTE", "AFFE", "ELCH", "MUECKE", "MOTTE", "BERGZIEGE",
    "MAUS", "MAULTIER", "NARWAL", "MOLCH", "OKTOPUS", "OPOSSUM", "ORANG-UTAN", "STRAUSS", "OTTER", "EULE",
    "OCHSE", "AUSTER", "PANTHER", "PAPAGEI", "PFAU", "PELIKAN", "PINGUIN", "SCHWEIN", "TAUBE", "PIRANHA",
    "SCHNABELTIER", "EISBAER", "PONY", "STACHELSCHWEIN", "GOTTESANBETERIN", "PAPAGEITAUCHER", "MOPS", "PUMA",
    "KANINCHEN", "WASCHBAER", "WIDDER", "RATTE", "KLAPPERSCHLANGE", "RABE", "RENTIER", "NASHORN",
    "WEGRENNER", "HAHN", "SALAMANDER", "LACHS", "SEELOEWE", "SEEOTTER", "MEERESSCHILDKROETE",
    "SEEPFERDCHEN", "ROBBE", "HAI", "SCHAF", "GARNELE", "STINKTIER", "FAULTIER", "NACKTSCHNECKE",
    "SCHNECKE", "SCHLANGE", "SPATZ", "SPINNE", "KALMAR", "EICHHOERNCHEN", "REHBOCK", "SEESTERN",
    "STACHELROCHEN", "STORCH", "SCHWAN", "VOGELSPINNE", "TERMITE", "TIGER", "KROETE", "LANDSCHILDKROETE",
    "TUKAN", "FORELLE", "THUNFISCH", "TRUTHAHN", "SCHILDKROETE", "WALROSS", "WARZENSCHWEIN", "WESPE",
    "WIESEL", "WALHAI", "GNU", "WOLF", "VIELFRASS", "WOMBAT", "SPECHT", "WURM", "YAK", "ZEBRA",
};

inline constexpr int kGermanAnimalCount = sizeof(kGermanAnimals) / sizeof(kGermanAnimals[0]);

// Index-aligned with the ACT IT OUT slice.
inline constexpr const char* kGermanAct[] = {
    "TUER OEFFNEN", "ARMDUEL", "KUCHEN BACKEN", "GEKITZELT WERDEN", "KUSSHAND GEBEN", "SEIFENBLASEN MACHEN",
    "VERBEUGEN", "BOXEN", "HAARE FLECHTEN", "SCHLUSS MACHEN", "ZAEHNE PUTZEN", "MAUER BAUEN", "TRAGEN",
    "FANGEN", "BUS HINTERHERLAUFEN", "AUF DIE UHR SEHEN", "KAUGUMMI KAUEN", "HOLZ HACKEN", "KLATSCHEN",
    "PUTZEN", "KLETTERN", "AM SEIL KLETTERN", "HAARE KAEMMEN", "KOCHEN", "EI AUFSCHLAGEN", "KRABBELN",
    "WEINEN", "NAEGEL SCHNEIDEN", "TANZEN", "BALLETT TANZEN", "KARTEN GEBEN", "LOCH GRABEN", "TAUCHEN",
    "RAD SCHLAGEN", "LIEGESTUETZE", "RUNTER", "BILD ZEICHNEN", "TRINKEN", "SUPPE TRINKEN", "AUTO FAHREN",
    "BUS FAHREN", "TROMMELN", "ESSEN", "SPAGHETTI ESSEN", "HINFALLEN", "EINSCHLAFEN", "BABY FUETTERN",
    "ANGELN", "MUSKELN ZEIGEN", "PFANNKUCHEN WENDEN", "DRACHEN STEIGEN LASSEN", "WAESCHE FALTEN", "GURGELN",
    "HAARE SCHNEIDEN LASSEN", "REDE HALTEN", "TAXI RUFEN", "NAGEL EINSCHLAGEN", "ABKLATSCHEN", "BERGAUF WANDERN",
    "TRAMPEN", "LUFT ANHALTEN", "UMARMEN", "SCHLITTSCHUHLAUFEN", "HEMD BUEGELN", "JOGGEN", "JONGLIEREN",
    "SPRINGEN", "SEILSPRINGEN", "TRETEN", "BALL TRETEN", "TEIG KNETEN", "STRICKEN", "ANKLOPFEN", "LACHEN",
    "EIS LECKEN", "HEBEN", "GEWICHTE HEBEN", "HINKEN", "ZUHOEREN", "TUER ABSCHLIESSEN", "KUH MELKEN",
    "BODEN WISCHEN", "RASEN MAEHEN", "GLAS OEFFNEN", "WAND STREICHEN", "HUND STREICHELN", "BANANE SCHAELEN",
    "AEPFEL PFLUECKEN", "KLAVIER SPIELEN", "GEIGE SPIELEN", "ZEIGEN", "TEE EINGIESSEN", "HEIRATSANTRAG MACHEN",
    "ZIEHEN", "AM SEIL ZIEHEN", "SCHIEBEN", "AUTO SCHIEBEN", "SOCKEN ANZIEHEN", "LAUB HARKEN", "LESEN",
    "KARTE LESEN", "PFERD REITEN", "ROLLER FAHREN", "BABY WIEGEN", "WUERFELN", "BOOT RUDERN", "RENNEN",
    "SEGELN", "SALUTIEREN", "SICH KRATZEN", "KNOPF ANNAEHEN", "HAENDE SCHUETTELN", "RASIEREN", "ZITTERN",
    "RUFEN", "SCHNEE SCHAUFELN", "KARTEN MISCHEN", "SINGEN", "SITZEN", "HINSETZEN", "SKATEBOARD FAHREN",
    "SKI FAHREN", "HUEPFEN", "TUER ZUSCHLAGEN", "SCHLAFEN", "SCHLAFWANDELN", "AN BLUMEN RIECHEN", "LAECHELN",
    "HERUMSCHLEICHEN", "NIESEN", "SCHNORCHELN", "ZITRONE AUSDRUECKEN", "STEHEN", "AUFSTEHEN", "STERNE BEOBACHTEN",
    "TOPF UMRUEHREN", "STRECKEN", "STREICHHOLZ ANZUENDEN", "SONNENBADEN", "SURFEN", "FLIEGE KLATSCHEN",
    "BODEN FEGEN", "SCHWIMMEN", "SCHLAEGER SCHWINGEN", "FOTO MACHEN", "STEPPTANZEN", "SUPPE PROBIEREN",
    "NACHDENKEN", "WERFEN", "FRISBEE WERFEN", "JEMANDEN KITZELN", "AUF ZEHEN GEHEN", "SEITE UMBLAETTERN",
    "KRAWATTE BINDEN", "SCHNELL TIPPEN", "GESCHENK AUSPACKEN", "HOCH", "STAUBSAUGEN", "ZU SPAET AUFWACHEN",
    "GEHEN", "HUND AUSFUEHREN", "AUTO WASCHEN", "HAENDE WASCHEN", "PFLANZEN GIESSEN", "WINKEN", "ABSCHIED WINKEN",
    "ENGE SCHUHE TRAGEN", "GEWICHTHEBEN", "FLUESTERN", "PFEIFEN", "ZWINKERN", "GESCHENK EINPACKEN", "SCHREIBEN",
    "BRIEF SCHREIBEN", "GAEHNEN", "JACKE ZUMACHEN",
};

inline constexpr int kGermanActCount = sizeof(kGermanAct) / sizeof(kGermanAct[0]);

// Index-aligned with the MAKE A SOUND slice.
inline constexpr const char* kGermanSound[] = {
    "FLUGZEUG", "ALARM", "WECKER", "KRANKENWAGEN", "APPLAUS", "LAWINE", "WEINENDES BABY", "DUDELSACK",
    "BANJO", "BIENENSTOCK", "FAHRRADKLINGEL", "VOGELGESANG", "MIXER", "KOCHENDER KESSEL", "SPRINGENDER BALL",
    "ZERBRECHENDES GLAS", "BLUBBERNDES WASSER", "RUELPSEN", "SUMMENDE BIENE", "KAMERAVERSCHLUSS", "AUTOALARM",
    "AUTOHUPE", "MIAUENDE KATZE", "SCHNURRENDE KATZE", "KETTENSAEGE", "JUBELNDE MENGE", "KIRCHENGLOCKEN",
    "KLATSCHEN", "HUSTEN", "MUHENDE KUH", "KNARRENDE TUER", "QUAKENDER FROSCH", "KNIRSCHEN", "LAUBKNIRSCHEN",
    "KUCKUCKSUHR", "BELLENDER HUND", "TUERKLINGEL", "TROPFENDER HAHN", "TROMMELWIRBEL", "BOHRMASCHINE",
    "ELEFANT", "FAXGERAET", "FEUERALARM", "FEUERWERK", "BRAUSEGETRAENK", "KLOSPUELUNG", "SCHRITTE",
    "GALOPPIERENDES PFERD", "GONG", "GITARRENSOLO", "SCHUSS", "HAEMMERN", "MUNDHARMONIKA", "HERZSCHLAG",
    "HUBSCHRAUBER", "ZISCHENDE SCHLANGE", "HEULENDER WIND", "HEULENDER WOLF", "EISWAGEN", "PRESSLUFTHAMMER",
    "DUESENTRIEBWERK", "PFEIFENDER KESSEL", "TASTATURTIPPEN", "KLOPFEN", "AUF HOLZ KLOPFEN", "LACHEN",
    "RASENMAEHER", "LICHTSCHWERT", "MASCHINENGEWEHR", "MARSCHKAPELLE", "MIKROWELLENPIEPS", "MUECKE", "MOTORRAD",
    "MEERESWELLEN", "OPERNSAENGER", "RUFENDE EULE", "TELEFONKLINGELN", "GRUNZENDES SCHWEIN", "TISCHTENNIS",
    "POLIZEISIRENE", "POPCORN", "POPPENDES POPCORN", "PLATZENDER BALLON", "REGEN", "REGEN AUF DEM DACH",
    "KLAPPERSCHLANGE", "AUFHEULENDER MOTOR", "BRUELLENDER LOEWE", "KRAEHENDER HAHN", "DONNERGROLLEN", "HOLZ SAEGEN",
    "SCHERE", "QUIETSCHENDE BREMSEN", "MOEWE", "BLOEKENDES SCHAF", "SIRENE", "BRUTZELN", "BRUTZELNDER SPECK",
    "QUIETSCHENDE REIFEN", "ZUSCHLAGENDE TUER", "SCHLUERFEN", "FINGER SCHNIPSEN", "NIESEN", "SCHNARCHEN",
    "PLATSCHEN", "QUIETSCHENDE SCHUHE", "DAMPFLOK", "BIENENSCHWARM", "TENNISAUFSCHLAG", "DONNER", "DONNERSCHLAG",
    "TICKENDE UHR", "TOASTER SPRINGT AUF", "ZUG", "ZUGHORN", "TROMPETE", "KOLLERNDER TRUTHAHN", "SCHREIBMASCHINE",
    "TIPPEN", "STAUBSAUGER", "GEIGE", "WASCHMASCHINE", "TROPFENDES WASSER", "WALGESANG", "TRILLERPFEIFE",
    "PFEIFEN", "WIND", "SCHEIBENWISCHER", "SPECHT", "REISSVERSCHLUSS",
};

inline constexpr int kGermanSoundCount = sizeof(kGermanSound) / sizeof(kGermanSound[0]);

// Index-aligned with the FOOD & DRINK slice.
inline constexpr const char* kGermanFood[] = {
    "APFEL", "APFELKUCHEN", "AVOCADO", "SPECK", "BAGEL", "BANANE", "BARBECUESOSSE", "BOHNEN", "GEBURTSTAGSKUCHEN",
    "HEIDELBEERE", "BROT", "BROKKOLI", "BROWNIE", "BUBBLE TEA", "BURGER", "BURRITO", "BUTTER", "KOHL", "KUCHEN",
    "CAPPUCCINO", "KARAMELL", "KAROTTE", "BLUMENKOHL", "SELLERIE", "CORNFLAKES", "KAESE", "CHEESEBURGER",
    "KAESEKUCHEN", "KIRSCHE", "KAUGUMMI", "HUHN", "HUEHNERSUPPE", "CHILI", "SCHOKOLADE", "SCHOKORIEGEL",
    "KOKOSNUSS", "KAFFEE", "COLA", "KEKS", "MAIS", "MAISKOLBEN", "CRANBERRY", "SAHNE", "CROISSANT", "GURKE",
    "CUPCAKE", "CURRY", "BITTERSCHOKOLADE", "DONUT", "TEIGTASCHE", "EI", "FISCH", "FISH AND CHIPS", "POMMES",
    "SPIEGELEI", "GEBRATENER REIS", "KNOBLAUCH", "LEBKUCHEN", "GRAPEFRUIT", "WEINTRAUBEN", "GRUENER TEE",
    "GUACAMOLE", "SCHINKEN", "HASELNUSS", "HONIG", "HEISSE SCHOKOLADE", "HOTDOG", "HUMMUS", "EISWUERFEL",
    "EISCREME", "EISKAFFEE", "MARMELADE", "GELEE", "SAFT", "KETCHUP", "KIWI", "LASAGNE", "ZITRONE", "LIMONADE",
    "KOPFSALAT", "MANGO", "MARSHMALLOW", "KARTOFFELBREI", "MAYONNAISE", "FLEISCHBAELLCHEN", "MELONE", "MILCH",
    "MILCHSHAKE", "MINZE", "MUESLI", "MUFFIN", "PILZ", "SENF", "NAAN", "NUDELN", "HAFERBREI", "OMELETT", "ZWIEBEL",
    "ORANGE", "ORANGENSAFT", "PFANNKUCHEN", "PAPAYA", "PASTA", "PFIRSICH", "ERDNUSSBUTTER", "BIRNE", "ERBSEN",
    "PEPPERONI", "PESTO", "ESSIGGURKE", "OBSTKUCHEN", "ANANAS", "PIZZA", "PFLAUME", "POPCORN", "KARTOFFEL",
    "KARTOFFELSALAT", "BREZEL", "PUDDING", "QUICHE", "ROSINE", "HIMBEERE", "RAVIOLI", "REIS", "BRATHAEHNCHEN",
    "SALAT", "SALAMI", "SALSA", "SALZ", "SANDWICH", "RUEHREI", "SMOOTHIE", "SUPPE", "SPAGHETTI", "SPINAT", "STEAK",
    "ERDBEERE", "ZUCKER", "ZUCKERWUERFEL", "SUSHI", "TACOS", "TEE", "TEEBEUTEL", "TOAST", "TOFFEE", "TOFU", "TOMATE",
    "TOMATENSUPPE", "TORTILLA", "TRUEFFEL", "VANILLE", "WAFFEL", "WASSER", "WASSERMELONE", "SCHLAGSAHNE", "JOGHURT",
};

inline constexpr int kGermanFoodCount = sizeof(kGermanFood) / sizeof(kGermanFood[0]);

// Index-aligned with the MOVIES slice. Established German release titles are
// used where they fit the card; internationally unchanged titles stay as-is.
inline constexpr const char* kGermanMovies[] = {
    "101 DALMATINER", "ALADDIN", "ALIEN", "ANASTASIA", "AVATAR", "ZURUECK IN DIE ZUKUNFT", "BAMBI", "BATMAN",
    "SCHOENE UND DAS BIEST", "BEETLEJUICE", "BLADE RUNNER", "MERIDA", "BRAVEHEART", "CARS", "CASABLANCA", "CHICAGO",
    "HENNEN RENNEN", "ASCHENPUTTEL", "COCO", "CORALINE", "ICH EINFACH UNVERB.", "STIRB LANGSAM", "DRACULA", "DUMBO",
    "DUNE", "E.T.", "ELF", "ENCANTO", "FANTASIA", "FINDET DORIE", "FINDET NEMO", "FORREST GUMP", "FRANKENSTEIN",
    "FREE WILLY", "DIE EISKOENIGIN", "DIE EISKOENIGIN 2", "GANDHI", "GHOSTBUSTERS", "GLADIATOR", "GODZILLA", "GREASE",
    "GREMLINS", "TAEGLICH GRUESST...", "HALLOWEEN", "HAPPY FEET", "HARRY POTTER", "HERCULES", "KEVIN ALLEIN ZU HAUS",
    "ICE AGE", "INCEPTION", "INDIANA JONES", "ALLES STEHT KOPF", "INTERSTELLAR", "IRON MAN", "DER WEISSE HAI", "JUMANJI",
    "JURASSIC PARK", "KING KONG", "KUNG FU PANDA", "LA LA LAND", "LILO UND STITCH", "MAD MAX", "MADAGASCAR", "MAMMA MIA",
    "MARY POPPINS", "MATILDA", "MEN IN BLACK", "MINIONS", "VAIANA", "DIE MONSTER AG", "MRS. DOUBTFIRE", "MULAN", "NARNIA",
    "NACHTS IM MUSEUM", "OCEAN'S ELEVEN", "PADDINGTON", "PETER PAN", "PINOCCHIO", "PRETTY WOMAN", "PSYCHO", "PULP FICTION",
    "RATATOUILLE", "ROBIN HOOD", "ROCKY", "RUSH HOUR", "SCARFACE", "SCHINDLERS LISTE", "SCOOBY-DOO", "SCREAM", "SHREK",
    "SHREK 2", "SING", "SKYFALL", "DORNROESCHEN", "SCHNEEWITTCHEN", "SPACE JAM", "SPIDER-MAN", "STAR TREK", "STAR WARS",
    "STUART LITTLE", "SUPERMAN", "RAPUNZEL", "TARZAN", "TAXI DRIVER", "DIE AVENGERS", "DIE CROODS", "DER EXORZIST",
    "DER PATE", "DIE GOONIES", "TRIBUTE VON PANEM", "DIE UNGLAUBLICHEN", "GIGANT AUS DEM ALL", "DAS DSCHUNGELBUCH",
    "KARATE KID", "THE LEGO MOVIE", "DER KOENIG DER LOEWEN", "ARIELLE MEERJUNGFRAU", "DER LORAX", "DIE MASKE", "MATRIX",
    "DIE MUMIE", "DIE MUPPETS", "WIE EIN EINZIGER TAG", "DIE BRAUT DES PRINZEN", "SHINING", "MEINE LIEDER", "TERMINATOR",
    "DER ZAUBERER VON OZ", "TITANIC", "TOY STORY", "TOY STORY 2", "TROLLS", "TWILIGHT", "OBEN", "WALL-E",
    "WALLACE UND GROMIT", "WILLY WONKA", "RALPH REICHTS", "ZOOMANIA",
};

inline constexpr int kGermanMovieCount = sizeof(kGermanMovies) / sizeof(kGermanMovies[0]);

// Index-aligned with the FAMOUS PEOPLE slice.
inline constexpr const char* kGermanPeople[] = {
    "ABRAHAM LINCOLN", "ADAM UND EVA", "ALBERT EINSTEIN", "ALEXANDER DER GROSSE", "ALFRED HITCHCOCK", "ALICE",
    "AMELIA EARHART", "ANDY WARHOL", "ANNE FRANK", "ARISTOTELES", "ASTERIX", "AUDREY HEPBURN", "BACH", "BARACK OBAMA",
    "BATMAN", "BEETHOVEN", "BILL GATES", "BOB MARLEY", "BRUCE LEE", "BUDDHA", "BUGS BUNNY", "BUZZ ALDRIN",
    "CAPTAIN AMERICA", "CHARLES DARWIN", "CHARLES DICKENS", "CHARLIE BROWN", "CHARLIE CHAPLIN", "CHOPIN", "ASCHENPUTTEL",
    "KLEOPATRA", "COCO CHANEL", "KONFUZIUS", "DAVID ATTENBOROUGH", "DAVID BOWIE", "DONALD DUCK", "DRACULA",
    "EDGAR ALLAN POE", "ELVIS PRESLEY", "FRANKENSTEIN", "FREDDIE MERCURY", "FRIDA KAHLO", "GALILEO", "GARFIELD",
    "DSCHINGIS KHAN", "GEORGE ORWELL", "GEORGE WASHINGTON", "HARRIET TUBMAN", "HARRY POTTER", "HENRY FORD", "HERKULES",
    "HOMER SIMPSON", "HOUDINI", "ISAAC NEWTON", "JAMES BOND", "JANE AUSTEN", "JIMI HENDRIX", "JOHN LENNON", "JULIA CHILD",
    "JULIUS CAESAR", "KOENIG ARTUS", "TUTANCHAMUN", "LEONARDO DA VINCI", "MADONNA", "MAHATMA GANDHI", "MARCO POLO",
    "MARIE CURIE", "MARILYN MONROE", "MARIO", "MARK TWAIN", "MARTIN LUTHER KING", "MARY SHELLEY", "MERLIN",
    "MICHAEL JACKSON", "MICHAEL JORDAN", "MICHELANGELO", "MICKEY MAUS", "MONET", "MOSES", "MUTTER TERESA", "MOZART",
    "MUHAMMAD ALI", "NAPOLEON", "NELSON MANDELA", "NIKOLA TESLA", "NOAH", "OSCAR WILDE", "PABLO PICASSO", "PELE",
    "PETER PAN", "PIKACHU", "PINOCCHIO", "PLATON", "POPEYE", "PRINCE", "PRINZESSIN DIANA", "PYTHAGORAS",
    "KOENIGIN VICTORIA", "ROALD DAHL", "ROBIN HOOD", "ROMEO UND JULIA", "SALVADOR DALI", "SAMUEL MORSE", "WEIHNACHTSMANN",
    "SCOOBY-DOO", "DAGOBERT DUCK", "SERENA WILLIAMS", "SHAKESPEARE", "SHERLOCK HOLMES", "SIGMUND FREUD", "SNOOPY",
    "SCHNEEWITTCHEN", "SOKRATES", "SPIDER-MAN", "SPONGEBOB", "STAN LEE", "STEPHEN HAWKING", "STEVE JOBS", "STEVIE WONDER",
    "SUPERMAN", "TARZAN", "DIE BEATLES", "DER HULK", "DER PAPST", "THOMAS EDISON", "TIM", "TOLKIEN", "TOM UND JERRY",
    "USAIN BOLT", "VINCENT VAN GOGH", "VIVALDI", "WALT DISNEY", "WINNIE PUUH", "WINSTON CHURCHILL", "WONDER WOMAN",
    "GEBRUEDER WRIGHT", "ZEUS",
};

inline constexpr int kGermanPeopleCount = sizeof(kGermanPeople) / sizeof(kGermanPeople[0]);

// Index-aligned with the MUSIC slice.
inline constexpr const char* kGermanMusic[] = {
    "AKKORDEON", "LUFTGITARRE", "ALBUM", "VERSTAERKER", "APPLAUS", "HINTER DER BUEHNE", "DUDELSACK", "BAND", "BANJO",
    "BEATBOXEN", "GLOCKE", "GEBURTSTAGSLIED", "BLUES", "GHETTOBLASTER", "MUSIKKASSETTE", "KASTAGNETTEN", "CELLO", "CHOR",
    "WEIHNACHTSLIED", "KIRCHENORGEL", "KLARINETTE", "KLASSIK", "KONZERT", "DIRIGENT", "CONGA-SCHLANGE", "COUNTRYMUSIK",
    "KUHGLOCKE", "PUBLIKUM", "BECKEN", "TANZFLAECHE", "DIDGERIDOO", "DISCO", "DJ", "KONTRABASS", "TROMMEL", "SCHLAGZEUGER",
    "TROMMELSTOECKE", "DUETT", "OHRWURM", "E-GITARRE", "FAHRSTUHLMUSIK", "ZUGABE", "FANFARE", "FESTIVAL", "FLAMENCO",
    "FLOETE", "VOLKSMUSIK", "WALDHORN", "GONG", "GITARRE", "MUNDHARMONIKA", "HARFE", "HEADBANGEN", "HAUPTKUENSTLER",
    "KOPFHOERER", "HEAVY METAL", "HOHER TON", "HIP-HOP", "JAZZ", "JUKEBOX", "KARAOKE", "KAZOO", "LIEBESLIED", "WIEGENLIED",
    "LIEDTEXT", "MARACAS", "MARIACHI", "METRONOM", "MIKROFON", "MOSHPIT", "SPIELUHR", "MUSIKNOTE", "NOTENSTAENDER",
    "MUSIKLEHRER", "MUSIKVIDEO", "MUSICAL", "NATIONALHYMNE", "KINDERREIM", "EINTAGSHIT", "VORGRUPPE", "OPER", "ORCHESTER",
    "PANFLOETE", "ABSOLUTES GEHOER", "KLAVIER", "PLAYLIST", "POPMUSIK", "POPSTAR", "PUNK", "RADIO", "RAP", "PLATTENSPIELER",
    "REGGAE", "REMIX", "KLINGELTON", "ROADIE", "ROCKMUSIK", "ROCKSTAR", "SAXOFON", "SERENADE", "NOTENBLATT", "MITSINGEN",
    "SAENGER", "SITAR", "LANGSAMER TANZ", "SONGSCHREIBER", "SOUNDCHECK", "FILMMUSIK", "LAUTSPRECHER", "SCHEINWERFER", "BUEHNE",
    "SINFONIE", "SYNTHESIZER", "TAMBOURIN", "TANGO", "TECHNO", "TICKET", "UNMUSIKALISCH", "VIOLINSCHLUESSEL", "TRIANGEL",
    "TRIO", "POSAUNE", "TROMPETE", "TUBA", "UKULELE", "SCHALLPLATTE", "GEIGE", "STIMME", "WALZER", "HOCHZEITSMARSCH",
    "WINDSPIEL", "WELTTOURNEE", "XYLOFON", "JODELN",
};

inline constexpr int kGermanMusicCount = sizeof(kGermanMusic) / sizeof(kGermanMusic[0]);

// Index-aligned with the JOBS slice.
inline constexpr const char* kGermanJobs[] = {
    "BUCHHALTER", "AKROBAT", "SCHAUSPIELER", "SANITAETER", "ANIMATOR", "ARCHAEOLOGE", "ARCHITEKT", "KUENSTLER",
    "ASTRONAUT", "ASTRONOM", "AUTOR", "BAECKER", "BALLERINA", "FRISEUR", "BARISTA", "BARKEEPER", "IMKER", "SCHMIED",
    "LEIBWAECHTER", "MAURER", "BAUARBEITER", "BUSFAHRER", "METZGER", "BUTLER", "KAMERAMANN", "TISCHLER", "CARTOONIST",
    "KASSIERER", "CHAUFFEUR", "KUECHENCHEF", "REINIGUNGSKRAFT", "CLOWN", "TRAINER", "KUESTENWACHE", "KOMIKER",
    "KOMPONIST", "DIRIGENT", "KOCH", "KURIER", "COWBOY", "TAENZER", "ZAHNARZT", "DETEKTIV", "DIPLOMAT", "DISC JOCKEY",
    "TAUCHER", "ARZT", "HUNDEAUSFUEHRER", "FAHRER", "SCHLAGZEUGER", "LEKTOR", "ELEKTRIKER", "INGENIEUR", "ENTDECKER",
    "BAUER", "MODEDESIGNER", "FEUERWEHRMANN", "FISCHER", "FLUGBEGLEITER", "FLORIST", "FUSSBALLSPIELER", "FOERSTER",
    "WAHRSAGER", "GAERTNER", "GEOLOGE", "TORWART", "WACHMANN", "FRISEUR", "HISTORIKER", "ILLUSTRATOR", "DOLMETSCHER",
    "ERFINDER", "HAUSMEISTER", "JUWELIER", "JOCKEY", "JOURNALIST", "RICHTER", "JONGLEUR", "ANWALT", "BIBLIOTHEKAR",
    "RETTUNGSSCHWIMMER", "SCHLOSSER", "HOLZFAELLER", "ZAUBERER", "BRIEFTRAEGER", "VISAGIST", "MATHEMATIKER", "MECHANIKER",
    "HEBAMME", "BERGMANN", "MUSIKER", "KINDERMAEDCHEN", "NACHRICHTENSPRECHER", "KRANKENPFLEGER", "OPTIKER", "MALER",
    "RETTUNGSSANITAETER", "PARKWAERTER", "APOTHEKER", "PHILOSOPH", "FOTOGRAF", "PILOT", "KLEMPNER", "DICHTER", "POLIZIST",
    "POLITIKER", "TOEPFER", "PRIESTER", "DRUCKER", "PROFESSOR", "PROGRAMMIERER", "PSYCHOLOGE", "VERLEGER", "PUPPENSPIELER",
    "RENNFAHRER", "REZEPTIONIST", "SCHIEDSRICHTER", "REPORTER", "SEEMANN", "VERKAEUFER", "WISSENSCHAFTLER", "BILDHAUER",
    "SICHERHEITSDIENST", "SCHAEFER", "SCHIFFSKAPITAEN", "LADENBESITZER", "SAENGER", "SOLDAT", "SPION", "CHIRURG", "SCHNEIDER",
    "TAETOWIERER", "TAXIFAHRER", "LEHRER", "REISEFUEHRER", "LOKFUEHRER", "UEBERSETZER", "NACHHILFELEHRER", "BESTATTER",
    "PLATZANWEISER", "TIERARZT", "KELLNER", "UHRMACHER", "SCHWEISSER", "FENSTERPUTZER", "SCHRIFTSTELLER", "TIERPFLEGER",
};

inline constexpr int kGermanJobCount = sizeof(kGermanJobs) / sizeof(kGermanJobs[0]);

// Index-aligned with the SPORTS slice.
inline constexpr const char* kGermanSports[] = {
    "AEROBIC", "BOGENSCHIESSEN", "ARMDUEL", "BADMINTON", "BALLETT", "BASEBALL", "BASKETBALL", "BEACHVOLLEYBALL",
    "BILLARD", "BINGO", "BMX", "BOBFAHREN", "BOWLING", "BOXEN", "BULLENREITEN", "BUNGEE-JUMPING", "KANUFAHREN",
    "KARTENSPIEL", "RAD SCHLAGEN", "FANGEN", "CHEERLEADING", "SCHACH", "KLETTERN", "CRICKET", "CROQUET", "CURLING",
    "RADFAHREN", "DARTS", "WASSERSPRINGEN", "VOELKERBALL", "DOMINO", "FECHTEN", "EISKUNSTLAUF", "ANGELN", "FUSSBALL",
    "FORMEL EINS", "FREISTOSS", "FRISBEE", "KARTFAHREN", "GOLF", "TURNEN", "HANDBALL", "DRACHENFLIEGEN",
    "VERSTECKSPIEL", "HOCHSPRUNG", "WANDERN", "HOCKEY", "HIMMEL UND HOELLE", "PFERDERENNEN", "HURDENLAUF",
    "EISHOCKEY", "SCHLITTSCHUHLAUFEN", "SPEERWURF", "JIU-JITSU", "JUDO", "JONGLIEREN", "SEILSPRINGEN", "SPRINGEN",
    "KARATE", "KAJAKFAHREN", "KICKBOXEN", "TRETEN", "KITESURFEN", "LACROSSE", "BOCKSPRINGEN", "WEITSPRUNG", "MARATHON",
    "MURMELN", "KAMPFSPORT", "MOTOCROSS", "MOUNTAINBIKEN", "OLYMPIA", "STAND-UP-PADDELN", "PAINTBALL", "FALLSCHIRMSPRUNG",
    "PARKOUR", "ELFMETER", "STABHOCHSPRUNG", "POLO", "POOLBILLARD", "RENNEN", "RAFTING", "RALLYEFAHREN", "STAFFELLAUF",
    "FELSKLETTERN", "RODEO", "ROLLSCHUHLAUFEN", "RUDERN", "RUGBY", "LAUFEN", "SEGELN", "GERAETETAUCHEN", "SKATEBOARDEN",
    "SCHLITTSCHUHLAUF", "SKI FAHREN", "FALLSCHIRMSPRINGEN", "RODELN", "SCHNORCHELN", "SNOWBOARDEN", "FUSSBALL", "SOFTBALL",
    "EISSCHNELLLAUF", "SPRINT", "SQUASH", "DEHNEN", "SUMORINGEN", "SURFEN", "SCHWIMMEN", "TISCHTENNIS", "FANGSPIEL",
    "TAI-CHI", "TANDEMRAD", "TENNIS", "WERFEN", "SEILTANZ", "LEICHTATHLETIK", "TRAMPOLINSPRINGEN", "TRIATHLON",
    "DREISPRUNG", "TAUZIEHEN", "ULTIMATE FRISBEE", "VOLLEYBALL", "GEHEN", "WASSERBALL", "WASSERSKI", "GEWICHTHEBEN",
    "WINDSURFEN", "RINGEN", "YOGA", "ZUMBA",
};

inline constexpr int kGermanSportCount = sizeof(kGermanSports) / sizeof(kGermanSports[0]);

// Index-aligned with the HOUSEHOLD slice.
inline constexpr const char* kGermanHouse[] = {
    "WECKER", "SCHUERZE", "SESSEL", "HINTERTUER", "BALKON", "VERBAND", "KORB", "BADEWANNE", "BETT", "BETTLAKEN",
    "NACHTTISCH", "DECKE", "MIXER", "BUECHERREGAL", "SCHUESSEL", "BROTKASTEN", "BESEN", "BUERSTE", "EIMER", "ETAGENBETT",
    "KALENDER", "KERZE", "TEPPICH", "DECKENVENTILATOR", "STUHL", "SCHORNSTEIN", "UHR", "KLEIDERSCHRANK", "COUCHTISCH",
    "KAMM", "COMPUTER", "KEKSDOSE", "COUCH", "TASSE", "KUECHENSCHRANK", "VORHANG", "KISSEN", "DARTSCHEIBE", "SCHREIBTISCH",
    "GESCHIRRTUCH", "SPUELMASCHINE", "TUER", "TUERKLINGEL", "BETTDECKE", "KAMIN", "TASCHENLAMPE", "BLUMENTOPF", "GABEL",
    "GEFRIERSCHRANK", "KUEHLSCHRANK", "HAUSTUER", "BRATPFANNE", "KLEBSTOFF", "HAARBUERSTE", "FOEHN", "FLUR", "HAMMER",
    "ZIMMERPFLANZE", "PUZZLE", "WASSERKOCHER", "SCHLUESSEL", "SCHLUESSELRING", "SPUELBECKEN", "MESSER", "LEITER",
    "LAMPENSCHIRM", "RASENMAEHER", "LICHT", "LICHTSCHALTER", "GLUEHBIRNE", "MATRATZE", "MIKROWELLE", "SPIEGEL", "WISCHMOPP",
    "BECHER", "NAGEL", "SERVIETTE", "BACKOFEN", "VORHAENGESCHLOSS", "TOPF", "PAPIER", "BUEROKLAMMER", "BLEISTIFT", "TELEFON",
    "BILD", "KOPFKISSEN", "KISSENBEZUG", "TELLER", "SAUGGLOCKE", "BLUMENTOPF", "HEIZKOERPER", "FERNBEDIENUNG", "SCHAUKELSTUHL",
    "QUIETSCHEENTE", "LAEUFER", "LINEAL", "KOCHTOPF", "SCHERE", "SCHRAUBENZIEHER", "REGAL", "SCHUHREGAL", "DUSCHE",
    "DUSCHVORHANG", "WASCHBECKEN", "SCHLAFSACK", "HAUSSCHUHE", "SEIFE", "SOFA", "SCHLAFSOFA", "SCHWAMM", "LOEFFEL", "TREPPE",
    "HEFTER", "TRITTLEITER", "HOCKER", "SCHALTER", "TISCH", "TISCHDECKE", "KLEBEBAND", "TEEKANNE", "FERNSEHER", "THERMOSTAT",
    "TOASTER", "TOILETTE", "KLOBUERSTE", "WERKZEUGKASTEN", "ZAHNBUERSTE", "HANDTUCH", "MUELLEIMER", "SCHIRMSTAENDER",
    "STAUBSAUGER", "VASE", "TAPETE", "WASCHMASCHINE", "FENSTER", "WEINGLAS",
};

inline constexpr int kGermanHouseCount = sizeof(kGermanHouse) / sizeof(kGermanHouse[0]);

// Index-aligned with the PLACES slice.
inline constexpr const char* kGermanPlaces[] = {
    "FLUGHAFEN", "ALASKA", "ALPEN", "AMAZONAS", "AMSTERDAM", "ANTARKTIS", "ARGENTINIEN", "ATHEN", "AUSTRALIEN", "BALI",
    "BANGKOK", "BANK", "BARCELONA", "STRAND", "PEKING", "BERLIN", "BIG BEN", "BRASILIEN", "BRUECKE", "KAIRO", "KANADA",
    "KAPSTADT", "KARIBIK", "BURG", "CHILE", "CHINA", "KIRCHE", "KOLOSSEUM", "KUBA", "DAENEMARK", "DUBAI", "DUBLIN",
    "EDINBURGH", "AEGYPTEN", "EIFFELTURM", "EVEREST", "BAUERNHOF", "FINNLAND", "FLORENZ", "FRANKREICH", "DEUTSCHLAND",
    "GRAND CANYON", "CHINESISCHE MAUER", "GRIECHENLAND", "GROENLAND", "HAWAII", "HIMALAYA", "HOLLYWOOD", "HONGKONG",
    "KRANKENHAUS", "HOTEL", "UNGARN", "ISLAND", "INDIEN", "IRLAND", "ISRAEL", "ISTANBUL", "ITALIEN", "JAMAIKA", "JAPAN",
    "JERUSALEM", "JORDANIEN", "KENIA", "KYOTO", "LAS VEGAS", "BIBLIOTHEK", "LISSABON", "LONDON", "LOS ANGELES",
    "MADAGASKAR", "MADRID", "MARKT", "MEXIKO", "MIAMI", "MAILAND", "MONTREAL", "MAROKKO", "MOSKAU", "KINO", "MUMBAI",
    "MUSEUM", "NAIROBI", "NEPAL", "NEW ORLEANS", "NEW YORK", "NEUSEELAND", "NIL", "NORDPOL", "NORWEGEN", "OXFORD", "PARIS",
    "PARK", "PERU", "PHILIPPINEN", "PISA", "POLEN", "PORTUGAL", "POSTAMT", "PYRAMIDEN", "RESTAURANT", "RIO DE JANEIRO",
    "ROM", "RUSSLAND", "SAHARA", "SAN FRANCISCO", "SCHULE", "SCHOTTLAND", "SEOUL", "SHANGHAI", "SIZILIEN", "SINGAPUR",
    "SUEDAFRIKA", "SPANIEN", "BAHNHOF", "FREIHEITSSTATUE", "STOCKHOLM", "STONEHENGE", "SUPERMARKT", "SCHWEDEN", "SCHWEIZ",
    "SYDNEY", "TAJ MAHAL", "THAILAND", "TIBET", "TOKIO", "TORONTO", "TUERKEI", "TOSKANA", "VATIKANSTADT", "VENEDIG", "WIEN",
    "VIETNAM", "WALES", "WARSCHAU", "WASHINGTON DC", "ZOO", "ZUERICH",
};

inline constexpr int kGermanPlaceCount = sizeof(kGermanPlaces) / sizeof(kGermanPlaces[0]);

// Index-aligned with the NATURE slice.
inline constexpr const char* kGermanNature[] = {
    "EICHEL", "LAWINE", "BAMBUS", "BAUMRINDE", "STRAND", "SCHNEESTURM", "BLUETE", "FELSBLOCK", "BRISE", "BUSCH", "KAKTUS",
    "CANYON", "HOEHLE", "KLIPPE", "WOLKE", "KLEE", "SPINNENNETZ", "KORALLENRIFF", "MAISFELD", "KRATER", "MONDSICHEL",
    "NARZISSE", "GAENSEBLUEMCHEN", "LOEWENZAHN", "MORGENGRAUEN", "WUESTE", "TAU", "NIESELREGEN", "DUERRE", "DUENE",
    "DAEMMERUNG", "ERDBEBEN", "FINSTERNIS", "NADELBAUM", "HERBST", "FARN", "FEUER", "UEBERSCHWEMMUNG", "BLUME", "NEBEL",
    "WALD", "FOSSIL", "FROST", "VOLLMOND", "STURMBOE", "GEYSIR", "GLETSCHER", "GRAS", "HAGEL", "ERNTE", "HEUHAUFEN",
    "HECKE", "HUEGEL", "HURRIKAN", "EIS", "EISKAPPE", "EISBERG", "EISZAPFEN", "INSEL", "DSCHUNGEL", "SEE", "ERDRUTSCH",
    "LAVA", "BLATT", "BLITZ", "LILIE", "WIESE", "DUNST", "MONSUN", "MOND", "MONDLICHT", "BERG", "SCHLAMM", "NEST", "EICHE",
    "OASE", "OBSTGARTEN", "PALME", "KIESELSTEIN", "TANNENZAPFEN", "KIEFER", "TEICH", "PFUETZE", "STEINBRUCH", "TREIBSAND",
    "REGEN", "REGENBOGEN", "REGENWALD", "STROMSCHNELLEN", "FLUSS", "FLUSSUFER", "FELS", "ROSE", "SAND", "SANDSTURM",
    "BAUMSAFT", "MEER", "MUSCHEL", "SEETANG", "UFER", "STRAUCH", "SCHNEEREGEN", "SCHNEE", "SCHNEEWEHE", "SCHNEEFLOCKE",
    "ERDBODEN", "FRUEHLING", "TROPFSTEIN", "STERN", "STURM", "BACH", "SONNE", "SONNENSTRAHL", "SONNENBLUME", "SONNENAUFGANG",
    "SONNENUNTERGANG", "SUMPF", "DORN", "DONNER", "GEZEITEN", "TORNADO", "BAUM", "TSUNAMI", "STEPPENROLLER", "ZWEIG", "TAL",
    "VULKAN", "WASSERFALL", "WELLE", "WALDBRAND", "WEIDE", "WIND",
};

inline constexpr int kGermanNatureCount = sizeof(kGermanNature) / sizeof(kGermanNature[0]);

// Index-aligned with the SCIENCE slice.
inline constexpr const char* kGermanScience[] = {
    "SAEURE", "LUFTDRUCK", "ALGEN", "ALUMINIUM", "ARTERIE", "ASTEROID", "ASTRONAUT", "ATMOSPHAERE", "ATOM", "POLARLICHT",
    "LAWINE", "ACHSE", "WIRBELSAEULE", "BAKTERIEN", "GLEICHGEWICHT", "BATTERIE", "URKNALL", "SCHWARZES LOCH", "GEHIRN",
    "BUNSENBRENNER", "KALZIUM", "KOHLENSTOFF", "ZELLE", "CHROMOSOM", "STROMKREIS", "KLONEN", "KOMET", "KOMPASS", "COMPUTER",
    "LEITER", "STERNBILD", "KUPFER", "KRATER", "KRISTALL", "DINOSAURIERFOSSIL", "DNA", "ERDE", "ERDBEBEN", "ECHO", "FINSTERNIS",
    "ELEKTRIZITAET", "ELEKTRON", "ELEMENT", "ENERGIE", "AEQUATOR", "EVOLUTION", "EXPERIMENT", "KRAFT", "FORMEL", "REIBUNG",
    "GALAXIE", "GEN", "GLETSCHER", "SCHWERKRAFT", "GYROSKOP", "HELIUM", "WASSERSTOFF", "EISZEIT", "ISOLATOR", "EISEN", "JUPITER",
    "LABOR", "LASER", "LAVA", "LINSE", "HEBEL", "LICHTJAHR", "BLITZ", "MAGNET", "MARS", "MASSE", "MERKUR", "METEOR", "MIKROSKOP",
    "MILCHSTRASSE", "MINERAL", "SPIEGEL", "MOLEKUEL", "MOND", "MONDLANDUNG", "NEBEL", "NEPTUN", "NERV", "STICKSTOFF", "ZELLKERN",
    "UMLAUFBAHN", "SAUERSTOFF", "FALLSCHIRM", "PENDEL", "PERIODENSYSTEM", "FOTOSYNTHESE", "PLANET", "PLUTO", "PRISMA", "FLASCHENZUG",
    "STRAHLUNG", "RADIOWELLE", "REGENBOGEN", "REFLEX", "ROBOTER", "RAKETE", "SATELLIT", "SATURN", "SKELETT", "SOLARPANEL",
    "SONNENSYSTEM", "SCHALLWELLE", "RAUMSTATION", "LICHTGESCHWINDIGKEIT", "TROPFSTEIN", "STERN", "STATISCHE LADUNG", "STETHOSKOP",
    "SONNE", "SUPERNOVA", "TELESKOP", "THERMOMETER", "THERMOSTAT", "GEZEITEN", "GEWEBE", "TORNADO", "URANUS", "IMPFSTOFF", "VAKUUM",
    "VENUS", "VIRUS", "VULKAN", "WASSERKREISLAUF", "ROENTGENBILD", "SCHWERELOSIGKEIT",
};

inline constexpr int kGermanScienceCount = sizeof(kGermanScience) / sizeof(kGermanScience[0]);

}  // namespace forehead
