import os
import re
import gzip
import json

SRC_DIR = "src"
AVATAR_DIR = "assets_local/avatar"
AVATAR_MARKER = "/*__BATTLESHIP_AVATAR_SVGS__*/"


def minify_html(html: str) -> str:
    # Tags where whitespace should be preserved
    preserve_tags = ['pre', 'code', 'textarea', 'script', 'style']
    preserve_regex = '|'.join(preserve_tags)

    # Protect preserve blocks with placeholders
    preserve_blocks = []
    def preserve(match):
        preserve_blocks.append(match.group(0))
        return f"__PRESERVE_BLOCK_{len(preserve_blocks)-1}__"

    html = re.sub(rf'<({preserve_regex})[\s\S]*?</\1>', preserve, html, flags=re.IGNORECASE)

    # Remove HTML comments
    html = re.sub(r'<!--.*?-->', '', html, flags=re.DOTALL)

    # Collapse all whitespace between tags
    html = re.sub(r'>\s+<', '><', html)

    # Collapse multiple spaces inside tags
    html = re.sub(r'\s+', ' ', html)

    # Restore preserved blocks
    for i, block in enumerate(preserve_blocks):
        html = html.replace(f"__PRESERVE_BLOCK_{i}__", block)

    return html.strip()


def sanitize_identifier(name: str) -> str:
    """Sanitize a filename to create a valid C identifier."""
    sanitized = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    if sanitized and sanitized[0].isdigit():
        sanitized = f"_{sanitized}"
    return sanitized


def embed_battleship_avatars(content: str) -> str:
    if AVATAR_MARKER not in content:
        return content
    layers = {"base": "", "hair": {}, "eyes": {}, "mouth": {}}
    for file in sorted(os.listdir(AVATAR_DIR)):
        if not file.endswith('.svg'):
            continue
        path = os.path.join(AVATAR_DIR, file)
        with open(path, 'r', encoding='utf-8') as f:
            svg = re.sub(r'>\s+<', '><', f.read().strip())
        stem = file[:-4]
        if stem == 'base':
            layers['base'] = svg
            continue
        for kind in ('hair', 'eyes', 'mouth'):
            prefix = kind + '_'
            if stem.startswith(prefix):
                layers[kind][stem[len(prefix):]] = svg
                break
    if not layers['base']:
        raise RuntimeError('avatar base.svg missing')
    payload = 'const avatarSvg=' + json.dumps(layers, separators=(',', ':')) + ';'
    return content.replace(AVATAR_MARKER, payload, 1)


for root, _, files in os.walk(SRC_DIR):
    for file in files:
        if file.endswith(".html") or file.endswith(".js"):
            file_path = os.path.join(root, file)
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()

            if file.endswith(".html"):
                if file_path.endswith(os.path.join('apps_local', 'battleship', 'web', 'BattleshipPage.html')):
                    content = embed_battleship_avatars(content)
                processed = minify_html(content)
            else:
                processed = content

            compressed = gzip.compress(processed.encode('utf-8'), compresslevel=9)

            suffix = "Html" if file.endswith(".html") else "Js"
            base_name = sanitize_identifier(f"{os.path.splitext(file)[0]}{suffix}")
            header_path = os.path.join(root, f"{base_name}.generated.h")

            with open(header_path, "w", encoding="utf-8") as h:
                h.write(f"// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
                h.write(f"#pragma once\n")
                h.write(f"#include <cstddef>\n\n")
                h.write(f"constexpr char {base_name}[] PROGMEM = {{\n")

                for i in range(0, len(compressed), 16):
                    chunk = compressed[i:i+16]
                    hex_values = ', '.join(f'0x{b:02x}' for b in chunk)
                    h.write(f"  {hex_values},\n")

                h.write(f"}};\n\n")
                h.write(f"constexpr size_t {base_name}CompressedSize = {len(compressed)};\n")
                h.write(f"constexpr size_t {base_name}OriginalSize = {len(processed)};\n")

            print(f"Generated: {header_path}")
            print(f"  Original: {len(content)} bytes")
            print(f"  Minified: {len(processed)} bytes ({100*len(processed)/len(content):.1f}%)")
            print(f"  Compressed: {len(compressed)} bytes ({100*len(compressed)/len(content):.1f}%)")
